Proyecto_Personal_Marketplace/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('marketplace.urls')),
    path('user/', include('usuario.urls')),
    path('business/', include('marketplace_empresa.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

usuario/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'user'
urlpatterns = [
    path('<str:username>', views.ProfileView.as_view(), name='profile_detalle'),
    path('edit/<str:username>', views.ProfileEditView, name='editar_perfil'),
    path('register/', views.register, name='registration'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.core.exceptions import ValidationError
import re
from django.contrib.auth.models import User

# Clase Empresa
class Empresa(models.Model):
    nombre = models.CharField(max_length=50, verbose_name='Nombre', db_column='nombre')
    direccion = models.CharField(max_length=255, verbose_name='Direccion', db_column='direccion')
    pais = models.CharField(max_length=255, verbose_name='Pais', db_column='pais')

    class Meta:
        db_table= 'Empresa'
        verbose_name ='Empresa'
        verbose_name_plural ='Empresas'

    def __str__(self):
        return self.nombre



# Clase Usuario
class Profile(User):
    dni = models.CharField(max_length=9, unique=True, verbose_name='DNI', db_column='dni')
    correo = models.EmailField(unique=True, verbose_name='Correo Electronico', db_column='correo')
    imagen_perfil = models.ImageField(upload_to='usuarios/', verbose_name='Imagen de Perfil', db_column='imagen_perfil', blank=True, null=True, default='core/perfil_predeterminado.jpg')
    is_empresa = models.BooleanField(default=False, verbose_name='Quiere registrarse como empresa?', db_column='is_empresa')
    empresa_id = models.ForeignKey(to=Empresa, null=True, verbose_name='Empresa', db_column='empresa_id', on_delete=models.SET_NULL, default=None, related_name='get_Empresa_Usuarios', blank=True)


    class Meta:
        db_table= 'Profile'
        verbose_name ='Perfil'
        verbose_name_plural ='Perfiles'

    def clean(self):
        super().clean()

        
        if not re.match(r'^[0-9]{8}[A-Za-z]$', self.dni):
            raise ValidationError("El DNI debe tener 8 dígitos seguidos de una letra.")
        
       
        numeros = int(self.dni[:8])
        letra = self.dni[-1].upper()
        letras_dni = "TRWAGMYFPDXBNJZSQVHLCKE"
        letra_correcta = letras_dni[numeros % 23]

        if letra != letra_correcta:
            raise ValidationError(f"El DNI es incorrecto")
        
    def __str__(self):
        return super().username
    
#Clase Categoria
class Categoria(models.Model):
    nombre = models.CharField(max_length=30, primary_key=True, verbose_name='Nombre', db_column='nombre')
    
    class Meta:
        db_table= 'Categoria'
        verbose_name ='Categoria'
        verbose_name_plural ='Categorias'

#Clase SubCategoria
class SubCategoria(models.Model):
    nombre = models.CharField(max_length=30, verbose_name='Nombre', db_column='nombre')
    categoria_id = models.ForeignKey(to=Categoria, on_delete=models.CASCADE, verbose_name="Categoria", db_column="categoria", related_name='get_Categoria_SubCategoria')
    
    class Meta:
        db_table= 'SubCategoria'
        verbose_name ='SubCategoria'
        verbose_name_plural ='SubCategorias'

# Clase Producto
class Producto(models.Model):
    id = models.CharField(max_length=50, primary_key=True, verbose_name='ID', db_column='id')
    nombre = models.CharField(max_length=100, verbose_name='Nombre', db_column='nombre')
    imagen = models.ImageField(upload_to='productos/', verbose_name='Imagen de Producto', db_column='imagen')
    descripcion = models.TextField(verbose_name='Descripcion', db_column='descripcion')
    empresa_id = models.ForeignKey(to=Empresa, on_delete=models.CASCADE, verbose_name='Empresa', db_column='empresa_id', related_name='get_Empresa_Productos')
    subCategoria_id = models.ForeignKey(to=SubCategoria, on_delete=models.CASCADE, verbose_name='SubCategoria', db_column='subCategoria_id', related_name='get_SubCategoria_Productos')

    class Meta:
        db_table= 'Producto'
        verbose_name ='Producto'
        verbose_name_plural ='Productos'

    def __str__(self):
        return self.nombre

# Clase Oferta
class Producto_Listing(models.Model):
    precio = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Precio', db_column='precio')
    stock = models.PositiveIntegerField(verbose_name='Stock', db_column='stock')
    producto_id = models.ForeignKey(to=Producto, verbose_name='Producto', db_column='producto_id', on_delete=models.CASCADE, related_name='get_Producto_Ofertas')
    empresa_id = models.ForeignKey(to=Empresa, verbose_name='Empresa', db_column='empresa_id', on_delete=models.CASCADE, related_name='get_Empresa_Listing')
    
    class Meta:
        db_table= 'Producto_Listing'
        verbose_name ='Oferta'
        verbose_name_plural ='Ofertas'

    def __str__(self):
        return f"{self.producto_id.nombre} ofrecido por {self.empresa_id.nombre} a {self.precio} €"
    



class Carrito_Detalle(models.Model):
    unidades = models.PositiveIntegerField(verbose_name='Unidades', db_column='unidades')
    estado_venta = models.BooleanField(default=False, verbose_name='Estado', db_column='estado_venta')
    user_id = models.ForeignKey(to=Profile, on_delete=models.CASCADE, verbose_name='Usuario', db_column='user_id' , related_name='get_Usuario_Carritos')
    producto_listing_id = models.ForeignKey(to=Producto_Listing, verbose_name='Oferta', db_column='producto_listing_id', on_delete=models.CASCADE, related_name='get_ProductoListing_CarritoDetalles')
    

    class Meta:
        db_table= 'Carrito_Detalle'
        verbose_name ='Detalle Carrito'
        verbose_name_plural ='Detalle Carrito'


class Venta(models.Model):
    fecha = models.DateTimeField()
    user_id = models.ForeignKey(to=Profile, on_delete=models.CASCADE, verbose_name='Usuario', db_column='user_id' , related_name='get_Usuario_Factura')
    carrito_detalle_id = models.ManyToManyField(to=Carrito_Detalle, verbose_name='Detalle Carrito', db_column='carrito_detalle_id', related_name='get_Usuario_Factura')

    class Meta:
        db_table= 'Factura'
        verbose_name ='Factura'
        verbose_name_plural ='Facturas'   

core/views.py
from django.shortcuts import render

# Create your views here.

core/templates/core/master.html
{% load static %}
<html
  lang="en"
  class="light-style layout-navbar-fixed layout-menu-fixed layout-compact"
  dir="ltr"
  data-theme="theme-default"
  data-assets-path="{% static 'core/' %}/src/assets/"
  data-template="vertical-menu-template-starter"
  data-style="light">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />

    <title>Deal Express</title>

    <meta name="description" content="" />

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'core/' %}/src/assets/img/favicon/favicon.ico" />

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&ampdisplay=swap"
      rel="stylesheet" />

    <link rel="stylesheet" href="{% static 'core/' %}/src/assets/vendor/fonts/tabler-icons.css" />
    <!-- <link rel="stylesheet" href="{% static 'core/' %}/src/assets/vendor/fonts/fontawesome.css" /> -->
    <!-- <link rel="stylesheet" href="{% static 'core/' %}/src/assets/vendor/fonts/flag-icons.css" /> -->

    <!-- Core CSS -->

    <link rel="stylesheet" href="{% static 'core/' %}/src/assets/vendor/css/rtl/core.css" class="template-customizer-core-css" />
    <link rel="stylesheet" href="{% static 'core/' %}/src/assets/vendor/css/rtl/theme-default.css" class="template-customizer-theme-css" />

    <link rel="stylesheet" href="{% static 'core/' %}/src/assets/css/demo.css" />

    <!-- Vendors CSS -->
    <link rel="stylesheet" href="{% static 'core/' %}/src/assets/vendor/libs/node-waves/node-waves.css" />

    <link rel="stylesheet" href="{% static 'core/' %}/src/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css" />

    <!-- Page CSS -->
    {% block css %}
    {% endblock css %}
    <!-- Helpers -->
    <script src="{% static 'core/' %}/src/assets/vendor/js/helpers.js"></script>
    <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->

    <!--? Template customizer: To hide customizer set displayCustomizer value false in config.js.  -->
    <script src="{% static 'core/' %}/src/assets/vendor/js/template-customizer.js"></script>

    <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->
    <script src="{% static 'core/' %}/src/assets/js/config.js"></script>
  </head>

  <body>
    <!-- Layout wrapper -->
    <div class="layout-wrapper layout-content-navbar">
      <div class="layout-container">
        <!-- Menu -->

        <aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
          <div class="app-brand demo">
            <a href="{% url 'index_marketplace' %}" class="app-brand-link">
              <span class="app-brand-logo demo">
                
                  <img width="52" height="72" viewBox="0 0 32 22" fill="none" src="/media/core/logo.png" alt="Image not found" />
                  
              </span>
              <span class="app-brand-text demo menu-text fw-bold">Deal Express</span>
            </a>

            <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto">
              <i class="ti menu-toggle-icon d-none d-xl-block align-middle"></i>
              <i class="ti ti-x d-block d-xl-none ti-md align-middle"></i>
            </a>
          </div>

          <div class="menu-inner-shadow"></div>

          <ul class="menu-inner py-1">
            <!-- Page -->
            <li class="menu-item active">
              <a href="{% url 'index_marketplace' %}" class="menu-link">
                <i class="menu-icon tf-icons ti ti-smart-home"></i>
                <div data-i18n="Page 1">Shopping</div>
              </a>
            </li>
            {% for group in user.groups.all %}
              {% if group.name == "Empresa" %}
                <li class="menu-item active">
                  <a href="{% url 'index_marketplace_empresa' %}" class="menu-link">
                    <i class="menu-icon tf-icons ti ti-smart-home"></i>
                    <div data-i18n="Page 1">Empresa</div>
                  </a>
                </li>
              {% endif %}
            {% endfor %}
            {% block navLateral %}
            {% endblock navLateral %}
          </ul>
        </aside>
        <!-- / Menu -->

        <!-- Layout container -->
        <div class="layout-page">
          <!-- Navbar -->

          <nav
            class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme"
            id="layout-navbar">
            <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
              <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
                <i class="ti ti-menu-2 ti-md"></i>
              </a>
            </div>

            <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
              <div class="navbar-nav align-items-center">
                <div class="nav-item dropdown-style-switcher dropdown">
                  <a
                    class="nav-link btn btn-text-secondary btn-icon rounded-pill dropdown-toggle hide-arrow"
                    href="javascript:void(0);"
                    data-bs-toggle="dropdown">
                    <i class="ti ti-md"></i>
                  </a>
                  <ul class="dropdown-menu dropdown-menu-start dropdown-styles">
                    <li>
                      <a class="dropdown-item" href="javascript:void(0);" data-theme="light">
                        <span class="align-middle"><i class="ti ti-sun me-3"></i>Light</span>
                      </a>
                    </li>
                    <li>
                      <a class="dropdown-item" href="javascript:void(0);" data-theme="dark">
                        <span class="align-middle"><i class="ti ti-moon-stars me-3"></i>Dark</span>
                      </a>
                    </li>
                    <li>
                      <a class="dropdown-item" href="javascript:void(0);" data-theme="system">
                        <span class="align-middle"><i class="ti ti-device-desktop-analytics me-3"></i>System</span>
                      </a>
                    </li>
                  </ul>
                </div>
              </div>

              <ul class="navbar-nav flex-row align-items-center ms-auto">




                {% if user.is_authenticated %}
                <!-- User -->
                <li class="nav-item navbar-dropdown dropdown-user dropdown">
                  <a
                    class="nav-link dropdown-toggle hide-arrow p-0"
                    href="javascript:void(0);"
                    data-bs-toggle="dropdown">
                    <div class="avatar avatar-online">
                      <img src="{{ user.profile.imagen_perfil.url }}" alt class="rounded-circle" />
                    </div>
                  </a>
                  <ul class="dropdown-menu dropdown-menu-end">
                    <li>
                      <a class="dropdown-item mt-0" href="{% url 'user:profile_detalle' username=user.username %}">
                        <div class="d-flex align-items-center">
                          <div class="flex-shrink-0 me-2">
                            <div class="avatar avatar-online">
                              <img src="{{ user.profile.imagen_perfil.url }}" alt class="rounded-circle" />
                            </div>
                          </div>
                          <div class="flex-grow-1">
                            <h6 class="mb-0">{{ user.username }}</h6>
                            {% for group in user.groups.all %}
                              {% if group.name == "Cliente" %}
                                <small class="text-muted">Cliente</small>
                              {% elif group.name == "Empresa" %}
                                <small class="text-muted">{{ user.profile.empresa_id.nombre }}</small>
                              {% endif %}
                            {% endfor %}

                            {% if user.is_superuser %}
                              <small class="text-muted">Administrador</small>
                            {% endif %}
                          </div>
                        </div>
                      </a>
                    </li>
                    <li>
                      <div class="dropdown-divider my-1 mx-n2"></div>
                    </li>
                    <li>
                      <a class="dropdown-item" href="{% url 'user:profile_detalle' username=user.username %}">
                        <i class="ti ti-user me-3 ti-md"></i><span class="align-middle">My Profile</span>
                      </a>
                    </li>
                    <li>
                      <div class="dropdown-divider my-1 mx-n2"></div>
                    </li>
                    <li>
                      <form action="{% url 'logout' %}" method="post">
                      {% csrf_token %}
                        <div class="d-grid px-2 pt-2 pb-1">
                          
                          <button class="btn btn-sm btn-danger d-flex" href="javascript:void(0);" type="submit">
                            <small class="align-middle">Logout</small>
                            <i class="ti ti-logout ms-2 ti-14px"></i>
                          </button>
                        
                        </div>
                      </form>
                    </li>
                  </ul>
                </li>
                <!--/ User -->
                {% else %}

                <li>
                  <a href="{% url 'login' %}" class="btn btn-primary waves-effect waves-light" target="_blank">
                    <span class="tf-icons ti ti-login scaleX-n1-rtl me-md-1"></span>
                    <span class="d-none d-md-block">Login</span>
                  </a>
                </li>

                {% endif %}



              </ul>
            </div>
          </nav>

          <!-- / Navbar -->

          <!-- Content wrapper -->
          <div class="content-wrapper">
            <!-- Content -->

            {% block content %}
            {% endblock content %}

            <!-- / Content -->

            <!-- Footer -->
            <footer class="content-footer footer bg-footer-theme">
              <div class="container-xxl">
                <div
                  class="footer-container d-flex align-items-center justify-content-between py-4 flex-md-row flex-column">
                  <div class="text-body">
                    ©
                    <script>
                      document.write(new Date().getFullYear());
                    </script>
                    Deal Express
                  </div>
                </div>
              </div>
            </footer>
            <!-- / Footer -->

            <div class="content-backdrop fade"></div>
          </div>
          <!-- Content wrapper -->
        </div>
        <!-- / Layout page -->
      </div>

      <!-- Overlay -->
      <div class="layout-overlay layout-menu-toggle"></div>

      <!-- Drag Target Area To SlideIn Menu On Small Screens -->
      <div class="drag-target"></div>
    </div>
    <!-- / Layout wrapper -->

    <!-- Core JS -->
    <!-- build:js assets/vendor/js/core.js -->

    <script src="{% static 'core/' %}/src/assets/vendor/libs/jquery/jquery.js"></script>
    <script src="{% static 'core/' %}/src/assets/vendor/libs/popper/popper.js"></script>
    <script src="{% static 'core/' %}/src/assets/vendor/js/bootstrap.js"></script>
    <script src="{% static 'core/' %}/src/assets/vendor/libs/node-waves/node-waves.js"></script>
    <script src="{% static 'core/' %}/src/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>
    <script src="{% static 'core/' %}/src/assets/vendor/libs/hammer/hammer.js"></script>

    <script src="{% static 'core/' %}/src/assets/vendor/js/menu.js"></script>

    <!-- endbuild -->

    <!-- Vendors JS -->

    <!-- Main JS -->
    <script src="{% static 'core/' %}/src/assets/js/main.js"></script>

    <!-- Page JS -->
    {% block javascript %}{% endblock javascript %}
  </body>
</html>